// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOllamaInstalled() {
  return window['go']['main']['App']['CheckOllamaInstalled']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function GenerateWithOllama(arg1, arg2) {
  return window['go']['main']['App']['GenerateWithOllama'](arg1, arg2);
}

export function GetInstalledModels() {
  return window['go']['main']['App']['GetInstalledModels']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OnEditorEvent(arg1, arg2) {
  return window['go']['main']['App']['OnEditorEvent'](arg1, arg2);
}

export function OnFileChange(arg1, arg2) {
  return window['go']['main']['App']['OnFileChange'](arg1, arg2);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFileByPath(arg1) {
  return window['go']['main']['App']['OpenFileByPath'](arg1);
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveFileAs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2, arg3);
}

export function StartOllamaServer() {
  return window['go']['main']['App']['StartOllamaServer']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
