// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMessage'](arg1, arg2, arg3);
}

export function CheckOllamaInstalled() {
  return window['go']['main']['App']['CheckOllamaInstalled']();
}

export function CheckOllamaServerRunning() {
  return window['go']['main']['App']['CheckOllamaServerRunning']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function CreateChat(arg1, arg2) {
  return window['go']['main']['App']['CreateChat'](arg1, arg2);
}

export function DeleteAllChats() {
  return window['go']['main']['App']['DeleteAllChats']();
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function ExportChat(arg1) {
  return window['go']['main']['App']['ExportChat'](arg1);
}

export function GenerateWithOllama(arg1, arg2) {
  return window['go']['main']['App']['GenerateWithOllama'](arg1, arg2);
}

export function GenerateWithOllamaStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateWithOllamaStream'](arg1, arg2, arg3, arg4);
}

export function GetChatContext(arg1, arg2) {
  return window['go']['main']['App']['GetChatContext'](arg1, arg2);
}

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetChats() {
  return window['go']['main']['App']['GetChats']();
}

export function GetInstalledModels() {
  return window['go']['main']['App']['GetInstalledModels']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OnEditorEvent(arg1, arg2) {
  return window['go']['main']['App']['OnEditorEvent'](arg1, arg2);
}

export function OnFileChange(arg1, arg2) {
  return window['go']['main']['App']['OnFileChange'](arg1, arg2);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFileByPath(arg1) {
  return window['go']['main']['App']['OpenFileByPath'](arg1);
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function RenameChatFromFirstMessage(arg1) {
  return window['go']['main']['App']['RenameChatFromFirstMessage'](arg1);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveFileAs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2, arg3);
}

export function SearchChats(arg1) {
  return window['go']['main']['App']['SearchChats'](arg1);
}

export function StartOllamaServer() {
  return window['go']['main']['App']['StartOllamaServer']();
}

export function StopGeneration(arg1) {
  return window['go']['main']['App']['StopGeneration'](arg1);
}

export function StopOllamaServer() {
  return window['go']['main']['App']['StopOllamaServer']();
}

export function UpdateChatTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatTitle'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
