// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckOllamaInstalled():Promise<main.OllamaStatus>;

export function ClearRecentFiles():Promise<void>;

export function GenerateWithOllama(arg1:string,arg2:string):Promise<string>;

export function GetInstalledModels():Promise<Array<main.OllamaModel>>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetSettings():Promise<main.Settings>;

export function Greet(arg1:string):Promise<string>;

export function NewFile():Promise<main.FileInfo>;

export function OnEditorEvent(arg1:string,arg2:main.EditorEventData):Promise<void>;

export function OnFileChange(arg1:string,arg2:boolean):Promise<void>;

export function OpenFile():Promise<main.FileOpenResult>;

export function OpenFileByPath(arg1:string):Promise<main.FileOpenResult>;

export function PullModel(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<main.FileInfo>;

export function SaveFileAs(arg1:string,arg2:string,arg3:string):Promise<main.FileInfo>;

export function StartOllamaServer():Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
