// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMessage(arg1:number,arg2:string,arg3:string):Promise<main.Message>;

export function CheckOllamaInstalled():Promise<main.OllamaStatus>;

export function CheckOllamaServerRunning():Promise<boolean>;

export function ClearRecentFiles():Promise<void>;

export function CreateChat(arg1:string,arg2:string):Promise<main.Chat>;

export function DeleteAllChats():Promise<void>;

export function DeleteChat(arg1:number):Promise<void>;

export function ExportAsPDF(arg1:string,arg2:string):Promise<void>;

export function ExportChat(arg1:number):Promise<string>;

export function GenerateWithOllama(arg1:string,arg2:string):Promise<string>;

export function GenerateWithOllamaStream(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetChatContext(arg1:number,arg2:number):Promise<string>;

export function GetChatMessages(arg1:number):Promise<Array<main.Message>>;

export function GetChats():Promise<Array<main.Chat>>;

export function GetInstalledModels():Promise<Array<main.OllamaModel>>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetSettings():Promise<main.Settings>;

export function Greet(arg1:string):Promise<string>;

export function NewFile():Promise<main.FileInfo>;

export function OnEditorEvent(arg1:string,arg2:main.EditorEventData):Promise<void>;

export function OnFileChange(arg1:string,arg2:boolean):Promise<void>;

export function OpenFile():Promise<main.FileOpenResult>;

export function OpenFileByPath(arg1:string):Promise<main.FileOpenResult>;

export function PullModel(arg1:string):Promise<void>;

export function RenameChatFromFirstMessage(arg1:number):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<main.FileInfo>;

export function SaveFileAs(arg1:string,arg2:string,arg3:string):Promise<main.FileInfo>;

export function SearchChats(arg1:string):Promise<Array<main.Chat>>;

export function StartOllamaServer():Promise<void>;

export function StopGeneration(arg1:string):Promise<void>;

export function StopOllamaServer():Promise<void>;

export function UpdateChatTitle(arg1:number,arg2:string):Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
